spring:
  application:
    name: account-service-eureka-feign-client
  mvc:
    view:
      prefix: /templates/
      suffix: .jsp

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
 